force-app/main/default/objects/Currency__c/Currency__c.object-meta.xml
<CustomObject>
    <description>An object to store Currency information like: Name, Symbol, Code, type, etc.</description>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Currency__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Currency__c/fields/USD_rate__c.field-meta.xml
<CustomField>
    <fullName>USD_rate__c</fullName>
    <label>USD rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Currency_Exchange_Rate__c/Currency_Exchange_Rate__c.object-meta.xml
<CustomObject>
    <description>Holds historical Currency exchange rates or currency convertions</description>
    <label>Currency Exchange Rate</label>
    <nameField>
        <displayFormat>CER-{000000000}</displayFormat>
        <label>Exchange Rate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Currency_Exchange_Rate__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAN</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>MXN</fullName>
            </value>
            <value>
                <fullName>CYN</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Currency_Exchange_Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Free_Currency_API_Key__mdt/Free_Currency_API_Key__mdt.object-meta.xml
<CustomObject>
    <label>Free Currency API Key</label>
    <pluralLabel>Free Currency API Key</pluralLabel>
</CustomObject>

force-app/main/default/classes/FreeCurrencyAPIService.cls
/**
 * @description       : Service methods for Free Currency API related operations against SF currency records
 * @author            : Arquimidez Mora
 * @group             : 
 * @last modified on  : 04-30-2025
 * @last modified by  : Arquimidez Mora
 * Modifications Log
 * Ver   Date         Author            Modification
 * 1.0   04-29-2025   Arquimidez Mora   Initial Version
**/
public with sharing class FreeCurrencyAPIService {
    
    /**
    * @description Gets the metadata records where the APIKey from Free Currency API is stored
    * @author Arquimidez Mora | 04-30-2025 
    * @return Free_Currency_API_Key__mdt 
    **/
    public static Free_Currency_API_Key__mdt retrieveAPIKey(){
        Free_Currency_API_Key__mdt objAPIKeyMDT = Free_Currency_API_Key__mdt.getInstance('FreeCurrencyAPI');
        return objAPIKeyMDT;
    }


    /**
    * @description Stores Currency data to SF
    * @author Arquimidez Mora | 04-30-2025 
    * @param List<Currency__c> lstCurrencyData 
    * @param List<Currency_Exchange_Rate__c> lstCurrencyRateData 
    * @return boolean 
    **/
    public static boolean saveCurrencies(List<Currency__c> lstCurrencyData, List<Currency_Exchange_Rate__c> lstCurrencyRateData){
        Boolean isSaveSuccess = saveRecordsByExternalIds(lstCurrencyData, Currency__c.Fields.Code__c);

        if(isSaveSuccess){
            isSaveSuccess = saveRecordsByExternalIds(lstCurrencyRateData, Currency_Exchange_Rate__c.Fields.Code__c);
            if(isSaveSuccess){
                List<Currency__c> lstCurrencies = new List<Currency__c>();
                for(Currency_Exchange_Rate__c objCurrencyRateData : lstCurrencyRateData){
                    Currency__c objCurrency = new Currency__c();
                    objCurrency.Code__c = objCurrencyRateData.Currency__c;
                    objCurrency.USD_rate__c = objCurrencyRateData.Rate__c;
                    lstCurrencies.add(objCurrency);
                }

                return saveRecordsByExternalIds(lstCurrencies, Currency__c.Fields.Code__c);
            }
        }

        return false;
    }

    /**
    * @description Stores Currency Rate data to SF
    * @author Arquimidez Mora | 04-30-2025 
    * @param List<Currency_Exchange_Rate__c> lstCurrencyRateData 
    * @return boolean 
    **/
    public static boolean saveCurrencyRates(List<Currency_Exchange_Rate__c> lstCurrencyRateData){
        return saveRecordsByExternalIds(lstCurrencyRateData, Currency_Exchange_Rate__c.Fields.Code__c);
    }

    /**
    * @description Upserts records to SF using external Id
    * @author Arquimidez Mora | 04-30-2025 
    * @param List<SObject> lstRecords 
    * @param Schema.SObjectField objExternalIdField 
    * @return Boolean 
    **/
    private static Boolean saveRecordsByExternalIds(List<SObject> lstRecords, Schema.SObjectField objExternalIdField){
        Boolean isSuccess = true;
        Database.UpsertResult[] srList = Database.upsert(lstRecords,objExternalIdField,false);
        for (Database.UpsertResult objSaveResult : srList) {
            if (!objSaveResult.isSuccess()) {
                isSuccess = false;
                for(Database.Error objError : objSaveResult.getErrors()) {
                    System.debug('An error has occurred. ' + objError.getStatusCode() + ': ' + objError.getMessage());
                    System.debug('Fields that affected this error: ' + objError.getFields());
                    
                }
            }
        }

        return isSuccess;
    }
}